"use strict";
(() => {
  const canvas=document.querySelector("#game-canvas"), ctx=canvas.getContext("2d",{alpha:false});
  const ui={modal:document.querySelector("#avatar-modal"),pauseOverlay:document.querySelector("#pause-overlay"),start:document.querySelector("#start-button"),pause:document.querySelector("#pause-button"),resume:document.querySelector("#resume-button"),music:document.querySelector("#background-music"),wheel:document.querySelector("#steering-wheel"),leftArrow:document.querySelector("#left-arrow"),rightArrow:document.querySelector("#right-arrow"),gas:document.querySelector("#gas-pedal"),brake:document.querySelector("#brake-pedal"),speed:document.querySelector("#speed-readout"),gear:document.querySelector("#gear-readout"),precision:document.querySelector("#precision-readout"),precisionBar:document.querySelector("#precision-bar"),driver:document.querySelector("#driver-readout"),role:document.querySelector("#driver-role"),difficulty:document.querySelector("#difficulty-readout"),difficultyLabel:document.querySelector("#difficulty-label"),status:document.querySelector("#status-label"),hint:document.querySelector("#drive-hint"),position:document.querySelector("#garage-position"),accelStat:document.querySelector("#accel-stat"),speedStat:document.querySelector("#speed-stat"),handlingStat:document.querySelector("#handling-stat")};
  const avatars={cyber:{name:"NEON CYBER",role:"VIOLET PULSE",accent:"#ff2ecf",accent2:"#27f2ff"},pro:{name:"BMW PRO",role:"ICE BLUE LINE",accent:"#27f2ff",accent2:"#d8f7ff"},bot:{name:"AI SYNTH BOT",role:"LIME CORE",accent:"#b7ff4b",accent2:"#27f2ff"}};
  const cars={i7:{name:"BMW i7",max:200,accel:89,handling:5.5,grip:.92,accent:"#53efff",accent2:"#d89aff",stats:[82,77,78]},fortuner:{name:"FORTUNER GR",max:180,accel:61,handling:3.8,grip:1.18,accent:"#ff5968",accent2:"#ffc54f",stats:[59,69,91]},bugatti:{name:"BUGATTI",max:260,accel:130,handling:8.6,grip:.75,accent:"#ff42d0",accent2:"#7d90ff",stats:[100,100,96]}};
  const order=["i7","fortuner","bugatti"];
  const state={running:false,paused:false,avatar:avatars.cyber,car:cars.i7,width:0,height:0,dpr:1,last:0,distance:0,speed:0,lateral:0,steer:0,wheelAngle:0,precision:98.4,difficulty:1,input:{left:false,right:false,gas:false,brake:false},touchSteering:false,particles:[]}; let selectedAvatar="cyber", selectedCar=0;
  const clamp=(n,min,max)=>Math.max(min,Math.min(max,n)),lerp=(a,b,t)=>a+(b-a)*t;
  function rgba(hex,a){const n=parseInt(hex.slice(1),16);return `rgba(${n>>16},${n>>8&255},${n&255},${a})`}
  function poly(p,fill,stroke,line=1){ctx.beginPath();p.forEach((q,i)=>i?ctx.lineTo(...q):ctx.moveTo(...q));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=line;ctx.stroke()}}
  function resize(){state.dpr=Math.min(devicePixelRatio||1,2);state.width=innerWidth;state.height=innerHeight;canvas.width=state.width*state.dpr;canvas.height=state.height*state.dpr;ctx.setTransform(state.dpr,0,0,state.dpr,0,0)} addEventListener("resize",resize,{passive:true});resize();
  function sky(t){const {width:w,height:h}=state,hy=h*.38;let g=ctx.createLinearGradient(0,0,0,hy);g.addColorStop(0,"#030518");g.addColorStop(.35,"#15245a");g.addColorStop(.72,"#7d246b");g.addColorStop(1,"#ff5eae");ctx.fillStyle=g;ctx.fillRect(0,0,w,hy);
    for(let i=0;i<5;i++){const x=((i*211+t*.006*(i+1))%(w+250))-125,y=48+i*30;const c=ctx.createRadialGradient(x,y,2,x,y,145);c.addColorStop(0,"rgba(139,169,255,.13)");c.addColorStop(1,"rgba(70,82,188,0)");ctx.fillStyle=c;ctx.fillRect(x-150,y-80,300,160)}
    const sunX=w*.51,sr=Math.min(96,w*.13),glow=ctx.createRadialGradient(sunX,hy-13,4,sunX,hy-13,sr*2.9);glow.addColorStop(0,"rgba(255,242,185,.93)");glow.addColorStop(.24,"rgba(255,94,186,.56)");glow.addColorStop(1,"rgba(202,45,187,0)");ctx.fillStyle=glow;ctx.fillRect(sunX-sr*3,hy-sr*3,sr*6,sr*3);ctx.fillStyle="#ffb7dc";ctx.beginPath();ctx.arc(sunX,hy-13,sr,Math.PI,0);ctx.lineTo(sunX+sr,hy);ctx.lineTo(sunX-sr,hy);ctx.fill();ctx.strokeStyle="rgba(105,19,112,.55)";ctx.lineWidth=3;for(let y=hy-sr+12;y<hy;y+=12){ctx.beginPath();ctx.moveTo(sunX-sr,y);ctx.lineTo(sunX+sr,y);ctx.stroke()}
    ctx.fillStyle="#080b22";for(let i=0;i<31;i++){let x=i*w/30,bh=15+((i*37)%65),bw=w*(.018+(i%4)*.009);ctx.fillRect(x,hy-bh,bw,bh);if(i%3===0){ctx.fillStyle="rgba(77,210,255,.38)";ctx.fillRect(x+bw*.25,hy-bh+7,2,3);ctx.fillStyle="#080b22"}}ctx.fillStyle="#070819";ctx.fillRect(0,hy,w,h-hy);
  }
  function roadside(cx,hy,t){const {width:w,height:h,distance,car}=state;for(let n=0;n<16;n++){const z=((n/16+distance*.016)%1),y=hy+z*z*(h-hy),xoff=lerp(w*.12,w*.95,z),side=n%2?-1:1,x=cx+side*xoff;ctx.globalAlpha=.18+.8*z;ctx.strokeStyle=n%3?rgba(car.accent,.82):rgba(car.accent2,.9);ctx.shadowBlur=12*z;ctx.shadowColor=ctx.strokeStyle;ctx.lineWidth=1+z*4;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,y-(12+65*z));ctx.stroke();if(n%4===0){ctx.beginPath();ctx.arc(x,y-(26+70*z),7+z*8,0,Math.PI*2);ctx.stroke()}}ctx.globalAlpha=1;ctx.shadowBlur=0}
  function road(t){const {width:w,height:h,distance,lateral,car}=state,hy=h*.385,top=w*.075,bottom=w*.66,cx=w*.5+lateral*w*.13,L=cx-top,R=cx+top,lb=cx-bottom,rb=cx+bottom;poly([[0,hy],[L,hy],[lb,h],[0,h]],"#071026");poly([[R,hy],[w,hy],[w,h],[rb,h]],"#071026");poly([[L,hy],[R,hy],[rb,h],[lb,h]],"#12132b");
    for(let n=0;n<44;n++){let z=(n/44+distance*.014)%1,y=hy+z*z*(h-hy),half=lerp(top,bottom,z);ctx.strokeStyle=n%5===0?rgba(car.accent,.42):"rgba(57,230,255,.13)";ctx.lineWidth=n%5===0?1.4:1;ctx.beginPath();ctx.moveTo(cx-half,y);ctx.lineTo(cx+half,y);ctx.stroke()}for(let x=-6;x<=6;x++){ctx.strokeStyle=x===0?rgba(car.accent2,.64):rgba(car.accent,.18);ctx.lineWidth=x===0?2:1;ctx.beginPath();ctx.moveTo(cx+x*top/3,hy);ctx.lineTo(cx+x*bottom/3,h);ctx.stroke()}
    for(let n=0;n<20;n++){let z=(n/20+distance*.023)%1,y=hy+z*z*(h-hy),dash=z*z*h*.045;ctx.strokeStyle="rgba(247,250,255,.72)";ctx.lineWidth=clamp(z*5,1,5);ctx.beginPath();ctx.moveTo(cx,y);ctx.lineTo(cx,y+dash);ctx.stroke()}roadside(cx,hy,t);
  }
  function particles(){const {width:w,height:h,speed,car}=state;if(speed>car.max*.57&&Math.random()<speed/car.max*.55)state.particles.push({x:w*.5+(Math.random()-.5)*w*.32,y:h*.72+Math.random()*h*.22,life:1,v:8+Math.random()*18});state.particles=state.particles.filter(p=>p.life>.04);state.particles.forEach(p=>{p.life-=.035;p.y+=p.v;ctx.strokeStyle=rgba(car.accent,p.life*.5);ctx.lineWidth=1+p.life*2;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x,p.y+p.v*2);ctx.stroke()})}
  function bodyBase(cw,ch,accent){poly([[-cw*.45,ch*.32],[-cw*.51,-ch*.03],[-cw*.32,-ch*.43],[-cw*.14,-ch*.62],[cw*.14,-ch*.62],[cw*.32,-ch*.43],[cw*.51,-ch*.03],[cw*.45,ch*.32]],"#111a30","#7280a5",2);poly([[-cw*.29,-ch*.35],[-cw*.14,-ch*.55],[cw*.14,-ch*.55],[cw*.29,-ch*.35],[cw*.22,-ch*.08],[-cw*.22,-ch*.08]],"#07111e",rgba(accent,.85),1.5);poly([[-cw*.5,-ch*.04],[-cw*.39,-ch*.27],[-cw*.28,-ch*.05],[-cw*.32,ch*.28],[-cw*.48,ch*.27]],"#05070d");poly([[cw*.5,-ch*.04],[cw*.39,-ch*.27],[cw*.28,-ch*.05],[cw*.32,ch*.28],[cw*.48,ch*.27]],"#05070d")}
  function drawI7(cw,ch){bodyBase(cw,ch,"#53efff");ctx.shadowBlur=19;ctx.shadowColor="#53efff";ctx.strokeStyle="#b7ffff";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-cw*.4,-ch*.01);ctx.lineTo(-cw*.19,-ch*.1);ctx.moveTo(cw*.4,-ch*.01);ctx.lineTo(cw*.19,-ch*.1);ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle="#071018";ctx.fillRect(-cw*.19,ch*.01,cw*.38,ch*.22);ctx.strokeStyle="#57f9ff";ctx.lineWidth=2;ctx.strokeRect(-cw*.19,ch*.01,cw*.38,ch*.22);ctx.strokeStyle="#de8eff";ctx.beginPath();ctx.moveTo(-cw*.34,ch*.28);ctx.lineTo(cw*.34,ch*.28);ctx.stroke()}
  function drawFortuner(cw,ch){ctx.translate(0,-ch*.06);bodyBase(cw*1.04,ch*1.17,"#ff5968");ctx.fillStyle="#101722";ctx.fillRect(-cw*.34,-ch*.61,cw*.68,ch*.08);ctx.strokeStyle="#ff5968";ctx.lineWidth=2;ctx.strokeRect(-cw*.34,-ch*.61,cw*.68,ch*.08);ctx.fillStyle="#070a0e";ctx.fillRect(-cw*.34,ch*.05,cw*.68,ch*.2);ctx.strokeStyle="#ff5968";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-cw*.42,ch*.08);ctx.lineTo(-cw*.25,ch*.02);ctx.moveTo(cw*.42,ch*.08);ctx.lineTo(cw*.25,ch*.02);ctx.stroke();ctx.fillStyle="#f84e5d";ctx.fillRect(-cw*.42,ch*.02,cw*.12,ch*.1);ctx.fillRect(cw*.3,ch*.02,cw*.12,ch*.1);ctx.translate(0,ch*.06)}
  function drawBugatti(cw,ch){bodyBase(cw*1.13,ch*.87,"#ff42d0");ctx.fillStyle="#060914";poly([[-cw*.48,ch*.27],[-cw*.25,ch*.02],[cw*.25,ch*.02],[cw*.48,ch*.27],[cw*.31,ch*.37],[-cw*.31,ch*.37]],"#060914");ctx.strokeStyle="#ff4fd4";ctx.shadowBlur=17;ctx.shadowColor="#ff4fd4";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-cw*.43,ch*.02);ctx.lineTo(cw*.43,ch*.02);ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle="#91a5ff";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-cw*.36,-ch*.5);ctx.lineTo(cw*.36,-ch*.5);ctx.stroke();ctx.fillStyle="#090914";ctx.fillRect(-cw*.13,ch*.08,cw*.26,ch*.2);ctx.strokeStyle="#ff6dde";ctx.strokeRect(-cw*.13,ch*.08,cw*.26,ch*.2)}
  function car(){const {width:w,height:h,steer,car}=state,cx=w*.5+steer*w*.045,cy=h*.79,sc=clamp(w/950,.62,1.15),cw=270*sc,ch=145*sc;ctx.save();ctx.translate(cx,cy);ctx.rotate(steer*.07);let sh=ctx.createRadialGradient(0,ch*.42,5,0,ch*.42,cw*.65);sh.addColorStop(0,"rgba(0,0,0,.9)");sh.addColorStop(1,"rgba(0,0,0,0)");ctx.fillStyle=sh;ctx.fillRect(-cw*.75,0,cw*1.5,ch*.7);if(car===cars.i7)drawI7(cw,ch);else if(car===cars.fortuner)drawFortuner(cw,ch);else drawBugatti(cw,ch);ctx.restore()}
  function render(t){sky(t);road(t);particles();car()}
  function update(dt){const i=state.input,c=state.car,target=(i.left?-1:0)+(i.right?1:0);if(!state.touchSteering)state.steer=lerp(state.steer,target,Math.min(1,dt*c.handling));const ratio=Math.max(0,state.speed)/c.max;state.difficulty=lerp(state.difficulty,1+ratio*.32,dt*1.5);if(i.gas)state.speed+=c.accel*(1-ratio*.42)*state.difficulty*dt;else state.speed-=18*c.grip*dt;if(i.brake)state.speed-=105*dt;state.speed=clamp(state.speed,-20,c.max);if(Math.abs(state.speed)<.3)state.speed=0;state.distance+=state.speed*dt*.13;state.lateral+=state.steer*(state.speed/c.max)*dt*(.24/c.grip);state.lateral=clamp(state.lateral,-.9,.9);state.precision=clamp(99.2-Math.abs(state.steer)*(2.1/c.grip)-Math.max(0,state.speed-c.max*.78)*.018,93.6,99.2);ui.speed.textContent=String(Math.round(Math.abs(state.speed))).padStart(3,"0");ui.gear.textContent=state.speed<-2?"R":state.speed<2?"N":"D";ui.precision.textContent=`${state.precision.toFixed(1)}%`;ui.precisionBar.style.width=`${state.precision}%`;ui.difficulty.textContent=`${state.difficulty.toFixed(2)}x`;ui.difficultyLabel.textContent=state.difficulty>1.22?"NEURAL PUSH":"CRUISE MODE";if(!state.touchSteering){state.wheelAngle=lerp(state.wheelAngle,state.steer*110,Math.min(1,dt*8));ui.wheel.style.transform=`rotate(${state.wheelAngle}deg)`}}
  function loop(t){if(!state.last)state.last=t;let dt=Math.min(.05,(t-state.last)/1000);state.last=t;if(state.running&&!state.paused)update(dt);render(t);requestAnimationFrame(loop)}requestAnimationFrame(loop);
  function input(key,val){state.input[key]=val}addEventListener("keydown",e=>{let m={ArrowLeft:"left",a:"left",A:"left",ArrowRight:"right",d:"right",D:"right",ArrowUp:"gas",w:"gas",W:"gas",ArrowDown:"brake",s:"brake",S:"brake"};if(m[e.key]){e.preventDefault();input(m[e.key],true)}if(e.key==="Escape"&&state.running)togglePause()});addEventListener("keyup",e=>{let m={ArrowLeft:"left",a:"left",A:"left",ArrowRight:"right",d:"right",D:"right",ArrowUp:"gas",w:"gas",W:"gas",ArrowDown:"brake",s:"brake",S:"brake"};if(m[e.key])input(m[e.key],false)});
  function touchButton(el,key){const sync=()=>el.classList.toggle("active",state.input[key]);el.addEventListener("pointerdown",e=>{e.preventDefault();el.setPointerCapture(e.pointerId);if(key==="left"||key==="right")state.touchSteering=false;input(key,true);sync()});["pointerup","pointercancel","lostpointercapture"].forEach(type=>el.addEventListener(type,()=>{input(key,false);sync()}))}touchButton(ui.gas,"gas");touchButton(ui.brake,"brake");touchButton(ui.leftArrow,"left");touchButton(ui.rightArrow,"right");
  function steer(e){let r=ui.wheel.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,a=clamp(Math.atan2(y,x)*180/Math.PI+90,-125,125);state.wheelAngle=a;state.steer=a/125;ui.wheel.style.transform=`rotate(${a}deg)`}ui.wheel.addEventListener("pointerdown",e=>{e.preventDefault();ui.wheel.setPointerCapture(e.pointerId);state.touchSteering=true;steer(e)});ui.wheel.addEventListener("pointermove",e=>state.touchSteering&&steer(e));["pointerup","pointercancel","lostpointercapture"].forEach(type=>ui.wheel.addEventListener(type,()=>state.touchSteering=false));
  function selectCar(index){selectedCar=(index+3)%3;let id=order[selectedCar],c=cars[id];document.querySelectorAll(".car-option").forEach(x=>x.classList.toggle("selected",x.dataset.car===id));ui.position.textContent=`0${selectedCar+1} / 03`;[ui.accelStat,ui.speedStat,ui.handlingStat].forEach((el,i)=>el.style.width=`${c.stats[i]}%`)}document.querySelector("#car-prev").addEventListener("click",()=>selectCar(selectedCar-1));document.querySelector("#car-next").addEventListener("click",()=>selectCar(selectedCar+1));document.querySelectorAll(".avatar").forEach(b=>b.addEventListener("click",()=>{selectedAvatar=b.dataset.avatar;document.querySelectorAll(".avatar").forEach(x=>x.classList.toggle("selected",x===b))}));selectCar(0);
  function togglePause(){if(!state.running)return;state.paused=!state.paused;ui.pauseOverlay.classList.toggle("hidden",!state.paused);ui.pause.textContent=state.paused?">":"II";ui.status.textContent=state.paused?"PAUSED":"ONLINE";if(state.paused)ui.music.pause();else ui.music.play().catch(()=>{})}ui.start.addEventListener("click",()=>{state.avatar=avatars[selectedAvatar];state.car=cars[order[selectedCar]];ui.driver.textContent=state.avatar.name;ui.role.textContent=`${state.avatar.role} / ${state.car.name}`;ui.modal.classList.add("hidden");state.running=true;ui.status.textContent="ONLINE";ui.hint.style.opacity="0";ui.music.volume=.42;ui.music.play().catch(()=>{})});ui.pause.addEventListener("click",togglePause);ui.resume.addEventListener("click",togglePause);
})();
